### ISSUE TITLE
ERROR: Failed to resolve: com.kirich1409.svgplugin:svg-glide4-plugin:1.1.1

### ISSUE THREAD

**Issue by TikTak123** [kirich1409/SvgGlidePlugins#5]
When I add a library to my project, I get an error
`ERROR: Failed to resolve: com.kirich1409.svgplugin:svg-glide4-plugin:1.1.1`

Here is my app module gradle
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.kirich1409.svgplugin:svg-glide4-plugin:1.1.1'
}
```

Here is my project module gradle
```
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}
```
I added jcenter()

How can I solve this?

**Comment by kirich1409** [comment]
I don't know why you have that issue, because the library has many downloads and published for more than 3-4 months. It will be good if you can attach a sample project with issues on your side

**Comment by kpradeepkumarreddy** [comment]
I'm also getting same error. Any solution for this ??
ERROR: Failed to resolve: com.kirich1409.svgplugin:glide4:1.1.1

**Comment by kpradeepkumarreddy** [comment]
> When I add a library to my project, I get an error
> `ERROR: Failed to resolve: com.kirich1409.svgplugin:svg-glide4-plugin:1.1.1`
> 
> Here is my app module gradle
> 
> ```
> dependencies {
>     implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation 'com.android.support:appcompat-v7:28.0.0'
>     implementation 'com.android.support.constraint:constraint-layout:1.1.3'
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'com.android.support.test:runner:1.0.2'
>     androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
>     implementation 'com.kirich1409.svgplugin:svg-glide4-plugin:1.1.1'
> }
> ```
> 
> Here is my project module gradle
> 
> ```
> allprojects {
>     repositories {
>         google()
>         jcenter()
>         mavenCentral()
>     }
> }
> ```
> 
> I added jcenter()
> 
> How can I solve this?

Did you find any solution for this ?? I also want to set svg files using Glide.

**Comment by kirich1409** [comment]
Try to add 
```groovy
maven { url = 'https://dl.bintray.com/kirich1409/maven' }
```
to repositories list

**Comment by amanzan** [comment]
I get the same error, and adding
```maven { url 'https://dl.bintray.com/kirich1409/maven' }```
doesn't solve the problem

Edit: it does solve the problem. You need to add it in allProjects, in your root build.gradle, like this:
```
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://jitpack.io'
        }
        maven { url 'https://dl.bintray.com/kirich1409/maven' }
    }
}
```
And then in your app build.gradle:
```
implementation 'com.kirich1409.svgplugin:svg-glide4-plugin:1.1.1'
```

Hope it helps

**Comment by abhimuktheeswarar** [comment]
@kirich1409 Please update your readme section:
It is mentioned as `implementation com.kirich1409.svgplugin:glide4:1.1.1`

**Comment by kirich1409** [comment]
I will publish minor update soon and after that update docs

**Comment by kirich1409** [comment]
Ready

**Comment by drakeet** [comment]
I am also getting the same error with `1.2.0`:

Both are `ERROR: Failed to resolve:`

```
implementation 'com.kirich1409.svgplugin:glide4:1.2.0'
// or
implementation 'com.kirich1409.svgplugin:svg-glide4-plugin:1.2.0'
```

**Comment by kirich1409** [comment]
Please, use my personal repository 
```groovy
repository {
   maven(url = 'https://dl.bintray.com/kirich1409/maven/')
}

implementation 'com.kirich1409.svgplugin:glide4:1.2.0'
```

I need time to find out the reason of the issue

**Comment by wasim-h-sheikh** [comment]
I am also getting same error. {ERROR: Failed to resolve}
where to put  below lines?
repository {
   maven(url = 'https://dl.bintray.com/kirich1409/maven/')
}

**Comment by arok** [comment]
Same issue for me. Also with `maven(url = 'https://dl.bintray.com/kirich1409/maven/')`
But it worked if I add dependency through Jitpack

**Comment by ymerzlikina** [comment]
> Please, use my personal repository
> 
> ```groovy
> repository {
>    maven(url = 'https://dl.bintray.com/kirich1409/maven/')
> }
> 
> implementation 'com.kirich1409.svgplugin:glide4:1.2.0'
> ```
> 
> I need time to find out the reason of the issue

Hello! Personal repository not worked. How I can download 1.2.0 version?

**Comment by kirich1409** [comment]
Hi. I will update the library today in the evening. It'll work tomorrow.

**Comment by ymerzlikina** [comment]
> Hi. I will update the library today in the evening. It'll work tomorrow.

Hello! com.kirich1409.svgplugin:glide4:1.2.0  not found at https://dl.bintray.com/kirich1409/maven/com/kirich1409/svgplugin/glide4/ :(

**Comment by kirich1409** [comment]
I didn’t find the problem. I don’t understand but the maven publisher plugin don’t wanna publish data properly. Will setup it from the beginning.

**Comment by kirich1409** [comment]
@ymerzlikina , try to check `com.kirich1409.svgplugin:svg-glide4-plugin:1.2.0`
